options:
  debug: false
  #生命值缩放
  health-scale: 20
  fight:
    #原版弓弩伤害会按攻击者射箭时的属性计算 而非射中时的
    arrow-cache-data: true
    #实体与实体间的战斗
    eve-fight-cal: false
    #战斗时间禁生命恢复系统
    disable-regain-on-fight: false
    attack-speed:
      #cooldown 物品冷却
      #vanilla 原版攻击速度机制
      type: cooldown
      #任何时间都能攻击(冷却不结束，就不能攻击)
      #伤害会被蓄力机制影响
      damage-any-time: true
      #蓄力机制 (已度过冷却时间/总时间)
      attack-force: true
      #蓄力百分比基于冷却
      #若false则为基于原版伤害
      force-based-cooldown: true
      #最小蓄力值 若蓄力开启 且 蓄力值小于此值则伤害取消
      min-force: 0.05
      #不冷却的材质
      no-cooldown-types:
        - "BOW"
        - "CROSSBOW"
    #无伤间隔/ 无敌帧
    #一个玩家打一次怪物 会有n tick 不能再伤害怪物
    no-damage-ticks:
      disable-world:
        - "example_world"
      #tick
      value: 5
    fight-status:
      #战斗状态持续时间
      #tick
      time: 100
    #是否开启原版最大生命值 (若不开启则完全接管)
    vanilla-max-health: true
    #是否开启原版移速 (若不开启则完全接管)
    vanilla-movement-speed: true
    #是否开启原版攻速 (若不开启则完全接管)
    vanilla-attack-speed: false
    #是否计算原版护甲
    vanilla-armor: true
    #是否开启原版回血
    vanilla-regain: true
    #这俩配置是为了用户能最大化定义距离攻击
    #比如说关闭这两个 自己写个特效机制
    distance-attack:
      #距离攻击的特效
      effect: true
      #距离攻击的声音
      sound: true
    #默认攻击距离
    #这里填原版的数值 建议不要改动
    #如果有偏差会导致 “二次伤害” 的触发
    vanilla-distance:
      default: 3
      creative: 4.5
    #禁止直接普攻的材质
    disable-damage-types:
      - "BOW"
      - "CROSSBOW"
    attack-fight: { }
    #若没有这些权限，则攻击时运行默认的 attack 战斗组
    #当攻击者拥有这个权限时，攻击时将运行 class-a-attack 战斗组
    #      as.class.a: class-a-attack
    # as.class.b: class-b-attack
  attribute:
    #tick
    time:
      #生命恢复间隔
      health-regain: 10
      #属性数据清理间隔
      attribute-clear: 1200
    #当行中有这些之一时，忽略此行属性
    ignores:
      - "//"
      - "§-"
    line-condition:
      #单行条件的格式
      #解析:
      # .* 匹配任意多个字符 : 用于匹配属性名及其值
      # \/ '\'用来转义，   :  属性和单行条件之间的分隔符
      # (?<requirement>.*) : 单行条件们
      # 例： 攻击力: 100/Lv.100,职业: 巫师
      format: '.*\/(?<requirement>.*)'
      #每个单行条件间的分隔符
      separator: ","
    base-attribute:
      #玩家基础属性
      player:
        - "生命恢复: 0.1"
        - "攻击速度: 1.5"
        - "命中几率: 100(%)"
        - "攻击距离: 2.7"
        - "暴击伤害: 150(%)"
      #其它实体基础属性
      entity:
        - "命中几率: 100(%)"
  #数字格式，这个最好不要乱动
  # ?<value>不要改，后面的正则可以改
  number-pattern: '(?<value>(\+|\-)?(\d+(?:(\.\d+))?))'
  string-append-separator: ", "
